### ISSUE TITLE
Not able to launch OiDuark

### ISSUE THREAD

**Issue by TapiocaFox** [SharpKoi/OiDuark#2]
Hello. Thanks for your works!
I've followed the guide from readme for Linux.
https://github.com/SharpKoi/OiDuark#linux

However when I type the command in terminal. The following happened.

![image](https://user-images.githubusercontent.com/22817012/179399524-3d946a17-28ce-4423-8672-7f733773c8da.png)

Am I doing anything wrong. Or how do I troubleshooting the problem. Thanks.

**Comment by SharpKoi** [comment]
Hi @magneticchen, 

Glad to have your report! The launcher seems to be broken. The new version has been released [here](https://github.com/SharpKoi/OiDuark/releases/tag/0.0.3-SNAPSHOT). You can follow the new instruction for Linux at [README](https://github.com/SharpKoi/OiDuark#linux) to install OiDuark. Alternatively, you can directly run the JAR by the commands:
```bash
cd oiduark-0.0.3-SNAPSHOT/bin
./java -Djdk.gtk.version=2 -jar oiduark.jar
```

Thanks for your following and feedback! 😊

**Comment by TapiocaFox** [comment]
Sure mate. I will check it out when available. Thanks for your response.
👍

**Comment by TapiocaFox** [comment]
Yep. It works. Thank U.
